export const FORM_ERRORS = 'خطاهای فرم را برطرف کنید'
export const SUCCESSFUL_OPERATION = 'عملیات با موفقیت انجام شد'
export const SUCCESSFUL_REMOVAL = 'حذف با موفقیت انجام شد'
export const EMPTY_DATA = 'دیتایی یافت نشد'
export const AXIOS_ERROR = 'خطایی رخ داده است'